######################################################################
# Automatically generated by qmake (2.01a) dim. dc. 5 14:09:53 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h \
    download.h \
    adddownload.h
SOURCES += main.cpp mainwindow.cpp \
    download.cpp \
    adddownload.cpp
RESOURCES += icons.qrc

QT += network

FORMS += \
    adddownload.ui
